/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmContainer: typeof import('./src/components/tool/ConfirmContainer.vue')['default']
    ContainerBar: typeof import('./src/components/container/ContainerBar.vue')['default']
    ContainerCol1: typeof import('./src/components/container/ContainerCol1.vue')['default']
    ContainerCol2: typeof import('./src/components/container/ContainerCol2.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    RiCircleFill: typeof import('@remixicon/vue')['RiCircleFill']
    RiCloseFill: typeof import('@remixicon/vue')['RiCloseFill']
    RiDeleteBin7Line: typeof import('@remixicon/vue')['RiDeleteBin7Line']
    RiEdit2Fill: typeof import('@remixicon/vue')['RiEdit2Fill']
    RiEditFill: typeof import('@remixicon/vue')['RiEditFill']
    RiLink: typeof import('@remixicon/vue')['RiLink']
    RiListUnordered: typeof import('@remixicon/vue')['RiListUnordered']
    RiLockLine: typeof import('@remixicon/vue')['RiLockLine']
    RiMailLine: typeof import('@remixicon/vue')['RiMailLine']
    RiMessageLine: typeof import('@remixicon/vue')['RiMessageLine']
    RiMoonLine: typeof import('@remixicon/vue')['RiMoonLine']
    RiMoreFill: typeof import('@remixicon/vue')['RiMoreFill']
    RiSunLine: typeof import('@remixicon/vue')['RiSunLine']
    RiTimeFill: typeof import('@remixicon/vue')['RiTimeFill']
    RiTimeLine: typeof import('@remixicon/vue')['RiTimeLine']
    RiTranslate2: typeof import('@remixicon/vue')['RiTranslate2']
    RiUser4Line: typeof import('@remixicon/vue')['RiUser4Line']
    RiUserLine: typeof import('@remixicon/vue')['RiUserLine']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingProfileForm: typeof import('./src/components/setting/SettingProfileForm.vue')['default']
    Temp: typeof import('./src/components/temp.vue')['default']
    TempCode: typeof import('./src/components/TempCode.vue')['default']
  }
}
