/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    RiArrowLeftSFill: typeof import('@remixicon/vue')['RiArrowLeftSFill']
    RiArrowUpWideLine: typeof import('@remixicon/vue')['RiArrowUpWideLine']
    RiBookmarkLine: typeof import('@remixicon/vue')['RiBookmarkLine']
    RiCircleFill: typeof import('@remixicon/vue')['RiCircleFill']
    RiCloseFill: typeof import('@remixicon/vue')['RiCloseFill']
    RiDeleteBin7Line: typeof import('@remixicon/vue')['RiDeleteBin7Line']
    RiDiscussLine: typeof import('@remixicon/vue')['RiDiscussLine']
    RiEdit2Fill: typeof import('@remixicon/vue')['RiEdit2Fill']
    RiEditFill: typeof import('@remixicon/vue')['RiEditFill']
    RiEditLine: typeof import('@remixicon/vue')['RiEditLine']
    RiFlaskLine: typeof import('@remixicon/vue')['RiFlaskLine']
    RiLink: typeof import('@remixicon/vue')['RiLink']
    RiListUnordered: typeof import('@remixicon/vue')['RiListUnordered']
    RiLoader3Line: typeof import('@remixicon/vue')['RiLoader3Line']
    RiLoader4Line: typeof import('@remixicon/vue')['RiLoader4Line']
    RiLockLine: typeof import('@remixicon/vue')['RiLockLine']
    RiMailLine: typeof import('@remixicon/vue')['RiMailLine']
    RiMessage3Line: typeof import('@remixicon/vue')['RiMessage3Line']
    RiMessageLine: typeof import('@remixicon/vue')['RiMessageLine']
    RiMoonLine: typeof import('@remixicon/vue')['RiMoonLine']
    RiMore2Fill: typeof import('@remixicon/vue')['RiMore2Fill']
    RiMoreFill: typeof import('@remixicon/vue')['RiMoreFill']
    RiRestartLine: typeof import('@remixicon/vue')['RiRestartLine']
    RiSunLine: typeof import('@remixicon/vue')['RiSunLine']
    RiTimeFill: typeof import('@remixicon/vue')['RiTimeFill']
    RiTimeLine: typeof import('@remixicon/vue')['RiTimeLine']
    RiTranslate2: typeof import('@remixicon/vue')['RiTranslate2']
    RiUser4Line: typeof import('@remixicon/vue')['RiUser4Line']
    RiUserLine: typeof import('@remixicon/vue')['RiUserLine']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
